services:
  postgres:
    image: postgres:15
    container_name: ilovesushi-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ilovesushi_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ilovesushi-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: ilovesushi-api
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres123@postgres:5432/ilovesushi_db
      - PORT=3001
    ports:
      - '3001:3001'
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - ilovesushi-network
    command: npm run dev

volumes:
  postgres_data:

networks:
  ilovesushi-network:
    driver: bridge
